apiVersion: v1
kind: PersistentVolume
metadata:
  name: bisque-testing-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cluster/data/bisque/testing-data"
