apiVersion: v1
kind: PersistentVolume
metadata:
  name: bisque-prod-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/cluster/data/bisque/production-data"
